Repository mui/pigment-css, pull requests merged in 2024-08, with the labels that each got.

#191 [TypeScript] Fix `sx` types and missing `style` prop from layout components
  packages/pigment-css-react/src/Box.d.ts
  packages/pigment-css-react/src/Container.d.ts
  packages/pigment-css-react/src/Grid.d.ts
  packages/pigment-css-react/src/Hidden.d.ts
  packages/pigment-css-react/src/Stack.d.ts
  packages/pigment-css-react/src/index.spec.ts
  packages/pigment-css-react/src/sx.d.ts
  packages/pigment-css-react/tests/Box.spec.tsx
  packages/pigment-css-react/tests/Container.spec.tsx
  packages/pigment-css-react/tests/Grid.spec.tsx
  packages/pigment-css-react/tests/Hidden.spec.tsx
  packages/pigment-css-react/tests/Stack.spec.tsx
  packages/pigment-css-react/tests/sx.spec.ts
Labels: bug 🐛, typescript

#196 [core] Fix thrown error during eval phase
  apps/pigment-css-next-app/src/app/grid/page.tsx
  packages/pigment-css-react/src/css.js
  packages/pigment-css-react/src/generateAtomics.js
  packages/pigment-css-react/src/globalCss.js
  packages/pigment-css-react/src/keyframes.js
  packages/pigment-css-react/src/useTheme.js
Labels: bug 🐛, component: Grid

#198 [core] Temporarily fallback to v5 of Material UI
  apps/pigment-css-next-app/next.config.js
  apps/pigment-css-next-app/package.json
  packages/pigment-css-react/package.json
  packages/pigment-css-react/src/processors/generateAtomics.ts
  packages/pigment-css-react/src/utils/processCssObject.ts
  packages/pigment-css-unplugin/package.json
  packages/pigment-css-vite-plugin/package.json
  pnpm-lock.yaml
Labels: typescript, core

#197 v0.0.19
  CHANGELOG.md
  package.json
  packages/pigment-css-nextjs-plugin/package.json
  packages/pigment-css-react/package.json
  packages/pigment-css-unplugin/package.json
  packages/pigment-css-vite-plugin/package.json
Labels: release

#200 [typescript] Fix `sx` types
  packages/pigment-css-react/src/sx.d.ts
Labels: typescript

#201 v0.0.20
  CHANGELOG.md
  package.json
  packages/pigment-css-nextjs-plugin/package.json
  packages/pigment-css-react/package.json
  packages/pigment-css-unplugin/package.json
  packages/pigment-css-vite-plugin/package.json
Labels: release

#214 Replace `endsWith` with `includes` to check adapter path
  packages/pigment-css-react/src/utils/preprocessor.ts
  packages/pigment-css-react/tests/testUtils.ts
  packages/pigment-css-react/tests/utils/adapter-path.test.ts
  packages/pigment-css-unplugin/src/index.ts
  packages/pigment-css-vite-plugin/src/vite-plugin.ts
Labels: enhancement

#218 [plugin] Fix bug related to path separator on Windows
  packages/pigment-css-unplugin/src/index.ts
  packages/pigment-css-vite-plugin/src/vite-plugin.ts
Labels: nextjs, vite
