Repository mui/pigment-css, pull requests merged in 2024-10, with the labels that each got.

#256 [core] Bump npx update-browserslist-db@latest
  pnpm-lock.yaml
Labels: bug 🐛, test, core, regression

#245 [docs] Fix git diff format
  README.md
Labels: docs

#266 [docs] Readme tweaks
  README.md
Labels: docs

#261 [docs] Fix syntax in JSDoc example
  packages/pigment-css-react/src/utils/extendTheme.ts
Labels: docs

#260 [docs] Fix broken link
  HOW_PIGMENT_CSS_WORKS.md
Labels: docs

#273 [code-infra] Remove releaseChangelog.mjs duplication
  package.json
  scripts/releaseChangelog.mjs
Labels: scope: code-infra

#272 [core] Remove <-- from changelog
  CHANGELOG.md
Labels: core

#274 [core] Upgrade @mui/monorepo
  package.json
  pnpm-lock.yaml
  stylelint.config.js
  stylelint.config.mjs
Labels: dependencies, scope: code-infra

#286 [react] Fix scoping issue with sx dynamic value transform
  packages/pigment-css-react/src/processors/sx.ts
  packages/pigment-css-react/src/utils/cssFnValueToVariable.ts
  packages/pigment-css-react/src/utils/sxObjectExtractor.ts
Labels: webpack, React

#277 [examples] Fix webpack CLI instructions
  examples/pigment-css-nextjs-ts/package.json
  examples/pigment-css-remix-ts/package.json
  examples/pigment-css-vite-ts/package.json
  examples/pigment-css-webpack-ts/README.md
  examples/pigment-css-webpack-ts/package.json
Labels: bug 🐛, examples, webpack

#287 v0.0.25
  CHANGELOG.md
  package.json
  packages/pigment-css-nextjs-plugin/package.json
  packages/pigment-css-react/package.json
  packages/pigment-css-unplugin/package.json
  packages/pigment-css-vite-plugin/package.json
Labels: release
