Repository mui/pigment-css, pull requests merged in 2024-09, with the labels that each got.

#222 [core] Fix CI with fake docs
  netlify.toml
  package.json
Labels: bug 🐛, core

#221 [core] Pin GitHub action dependency
  .github/workflows/ci.yml
Labels: core, security

#220 fix: styled-engine new internals
  packages/pigment-css-react/.gitignore
  packages/pigment-css-react/package.json
  packages/pigment-css-react/src/internal/index.ts
  packages/pigment-css-react/src/internal/styledEngineMockup.ts
  packages/pigment-css-react/tsup.config.ts
  packages/pigment-css-unplugin/src/index.ts
  packages/pigment-css-vite-plugin/src/vite-plugin.ts
Labels: enhancement

#224 v0.0.22
  CHANGELOG.md
  package.json
  packages/pigment-css-nextjs-plugin/package.json
  packages/pigment-css-react/package.json
  packages/pigment-css-unplugin/package.json
  packages/pigment-css-vite-plugin/package.json
Labels: release

#228 [nextjs] Move the import startsWith next check at end
  packages/pigment-css-nextjs-plugin/src/index.ts
Labels: nextjs

#229 Support null as a value for CSS object
  packages/pigment-css-react/src/utils/cssFnValueToVariable.ts
  packages/pigment-css-react/tests/styled/fixtures/styled-theme.input.js
  packages/pigment-css-react/tests/styled/fixtures/styled-theme.output.css
  packages/pigment-css-react/tests/styled/fixtures/styled-theme.output.js
  packages/pigment-css-react/tests/styled/styled.test.tsx
Labels: enhancement

#226 [next] Wrap all generated CSS with a cascade layer (WIP)
  packages/pigment-css-unplugin/src/index.ts
Labels: core

#230 [infra] Adds reusable workflow for new issue cleanup
  .github/workflows/issue-cleanup.yml
  .github/workflows/new-issue-triage.yml
Labels: scope: infra

#231 [infra] Adds reusable workflow for close issue message
  .github/workflows/closed-issue-message.yaml
Labels: scope: infra

#236 [nextjs] Fix react import check bug introduced in #228
  packages/pigment-css-nextjs-plugin/src/index.ts
Labels: bug 🐛, nextjs

#234 [react] Fix css extraction for transformed styled tagged-template call
  packages/pigment-css-react/src/processors/styled.ts
  packages/pigment-css-react/tests/styled/fixtures/styled-swc-transformed-tagged-string.input.js
  packages/pigment-css-react/tests/styled/fixtures/styled-swc-transformed-tagged-string.output.css
  packages/pigment-css-react/tests/styled/fixtures/styled-swc-transformed-tagged-string.output.js
  packages/pigment-css-react/tests/styled/styled.test.tsx
  packages/pigment-css-unplugin/src/index.ts
Labels: bug 🐛

#233 [Grid] ignore RSC error
  packages/pigment-css-react/src/Grid.jsx
  packages/pigment-css-react/tests/Grid/fixtures/Grid.output.js
Labels: bug 🐛, component: Grid

#241 V0.0.23
  CHANGELOG.md
  package.json
  packages/pigment-css-nextjs-plugin/package.json
  packages/pigment-css-react/package.json
  packages/pigment-css-unplugin/package.json
  packages/pigment-css-vite-plugin/package.json
Labels: release

#244 [docs] Correctly configure Vale
  .github/workflows/vale-action.yml
  .vale.ini
  CHANGELOG.md
  README.md
Labels: bug 🐛, docs

#243 feat: adapt to pre-processed styles
  packages/pigment-css-react/src/processors/styled.ts
Labels: package: system
