Repository mui/pigment-css, pull requests merged in 2024-11, with the labels that each got.

#294 core: Bump package versions and fix related TS errors
  apps/pigment-css-next-app/next.config.js
  apps/pigment-css-next-app/package.json
  apps/pigment-css-next-app/src/app/page.tsx
  apps/pigment-css-vite-app/package.json
  package.json
  packages/pigment-css-nextjs-plugin/src/virtual-css-loader.js
  packages/pigment-css-react/package.json
  packages/pigment-css-react/src/index.ts
  packages/pigment-css-react/src/processors/css.ts
  packages/pigment-css-react/src/processors/generateAtomics.ts
  packages/pigment-css-react/src/processors/globalCss.ts
  packages/pigment-css-react/src/processors/keyframes.ts
  packages/pigment-css-react/src/styled.d.ts
  packages/pigment-css-react/src/utils/processCssObject.ts
  packages/pigment-css-unplugin/package.json
  packages/pigment-css-unplugin/src/index.ts
  packages/pigment-css-vite-plugin/package.json
  pnpm-lock.yaml
Labels: bug 🐛

#299 [docs] Setup a new next.js application for documentation
  .eslintignore
  .eslintrc.js
  .gitignore
  docs/.eslintrc.js
  docs/.gitignore
  docs/README.md
  docs/data/getMarkdownPage.ts
  docs/data/getting-started/overview/overview.mdx
  docs/data/pages.ts
  docs/next.config.ts
  docs/package.json
  docs/src/app/(content)/getting-started/[slug]/not-found.tsx
  docs/src/app/(content)/getting-started/[slug]/page.tsx
  docs/src/app/(content)/layout.tsx
  docs/src/app/favicon.ico
  docs/src/app/fonts/GeistMonoVF.woff
  docs/src/app/fonts/GeistVF.woff
  docs/src/app/globals.css
  docs/src/app/layout.tsx
  docs/src/app/page.tsx
  docs/src/augment.d.ts
  docs/src/components/AppBar.tsx
  docs/src/components/DocsVersionSelector.tsx
  docs/src/components/EditPageOnGithub.tsx
  docs/src/components/IconButton.tsx
  docs/src/components/IconLinkButton.tsx
  docs/src/components/MainContent.tsx
  docs/src/components/Navigation.tsx
  docs/src/components/SiblingPageLinks.module.css
  docs/src/components/SiblingPageLinks.tsx
  docs/src/components/TableOfContents.tsx
  docs/src/components/Tooltip.tsx
  docs/src/components/icons/Github.tsx
  docs/src/components/icons/Pigment.tsx
  docs/src/components/icons/Select.tsx
  docs/src/components/icons/Settings.tsx
  docs/src/components/mdx/Callout.tsx
  docs/src/components/mdx/ComponentLinkedHeader.tsx
  docs/src/components/mdx/Description.tsx
  docs/src/components/mdx/MDXComponents.tsx
  docs/src/theme.ts
  docs/tsconfig.json
  package.json
  packages/pigment-css-nextjs-plugin/package.json
  packages/pigment-css-react/package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: scope: docs-infra

#292 [docs] Remove next tag from installation instructions
  README.md
Labels: docs

#254 [core] Increase the minimum Node.js version support to 14.0.0
  .browserslistrc
  packages/pigment-css-nextjs-plugin/package.json
  packages/pigment-css-react/package.json
  packages/pigment-css-unplugin/package.json
  packages/pigment-css-vite-plugin/package.json
Labels: breaking change, core

#306 [core] Fix Tidelift reference
  .github/FUNDING.yml
Labels: bug 🐛, core

#182 [nextjs] Fix tsconfig's path resolving
  apps/pigment-css-next-app/src/app/grid/page.tsx
  apps/pigment-css-next-app/src/components/Test.tsx
  apps/pigment-css-next-app/tsconfig.json
  packages/pigment-css-unplugin/src/index.ts
  pnpm-lock.yaml
Labels: nextjs

#308 v0.0.26
  CHANGELOG.md
  package.json
  packages/pigment-css-nextjs-plugin/package.json
  packages/pigment-css-react/package.json
  packages/pigment-css-unplugin/package.json
  packages/pigment-css-vite-plugin/package.json
Labels: release

#311 [core] Fix webpack capitalization
  docs/data/getting-started/overview/overview.mdx
  examples/pigment-css-webpack-ts/index.html
  packages/pigment-css-unplugin/package.json
Labels: docs, core

#310 [nextjs] Fix path resolution
  packages/pigment-css-unplugin/src/index.ts
Labels: bug 🐛, nextjs, webpack

#304 [docs] More docs infra changes
  docs/.env
  docs/.gitignore
  docs/globals.d.ts
  docs/next.config.ts
  docs/package.json
  docs/src/app/(content)/getting-started/[slug]/not-found.tsx
  docs/src/app/(content)/getting-started/[slug]/page.tsx
  docs/src/app/favicon.ico
  docs/src/app/globals.css
  docs/src/app/layout.tsx
  docs/src/components/AppBar.tsx
  docs/src/components/EditPageOnGithub.tsx
  docs/src/components/MainContent.tsx
  docs/src/components/SiblingPageLinks.tsx
  docs/src/components/icons/ChevronRight.tsx
  docs/src/utils/getMarkdownPage.ts
  docs/tsconfig.json
  package.json
  pnpm-lock.yaml
Labels: scope: docs-infra

#320 [react] Bump wyw versions
  packages/pigment-css-react/package.json
  packages/pigment-css-unplugin/package.json
  packages/pigment-css-vite-plugin/package.json
  pnpm-lock.yaml
Labels: nextjs, vite, React

#321 v0.0.27
  CHANGELOG.md
  package.json
  packages/pigment-css-nextjs-plugin/package.json
  packages/pigment-css-react/package.json
  packages/pigment-css-unplugin/package.json
  packages/pigment-css-vite-plugin/package.json
Labels: release

#271 [core] Fix test_types_next job
  .circleci/config.yml
Labels: bug 🐛, test, core, scope: code-infra

#325 [core] Add OpenSSF badge
  README.md
Labels: core

#330 [react] Mark prop-types as direct dependency
  packages/pigment-css-react/package.json
  pnpm-lock.yaml
Labels: bug 🐛
