Repository mui/pigment-css, pull requests merged in 2024-04, with the labels that each got.

#5 [docs] Fix README typos
  README.md
Labels: docs

#12 [core] Enable the CI
  .circleci/config.yml
  .codesandbox/ci.json
  package.json
  packages/pigment-css-react/package.json
  test/karma.tests.js
Labels: core

#14 [core] Enable ci/sandbox
  .codesandbox/ci.json
Labels: core

#15 [core] Remove paths associated with the @mui packages
  apps/pigment-css-next-app/README.md
  apps/pigment-css-vite-app/README.md
  packages/pigment-css-react/package.json
  packages/pigment-css-react/tsconfig.json
  packages/pigment-css-unplugin/tsconfig.json
  packages/pigment-css-vite-plugin/tsconfig.json
  pnpm-lock.yaml
Labels: core

#20 [docs] Update creating a new issue link
  HOW_PIGMENT_CSS_WORKS.md
Labels: docs

#19 [core] Add GitHub workflows
  .github/FUNDING.yml
  .github/ISSUE_TEMPLATE/1.bug.yml
  .github/ISSUE_TEMPLATE/2.feature.yml
  .github/ISSUE_TEMPLATE/3.rfc.yml
  .github/ISSUE_TEMPLATE/4.docs-feedback.yml
  .github/ISSUE_TEMPLATE/5.priority-support.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/PULL_REQUEST_TEMPLATE.md
  .github/codeql/codeql-config.yml
  .github/workflows/check-if-pr-has-label.yml
  .github/workflows/cherry-pick-next-to-master.yml
  .github/workflows/ci-check.yml
  .github/workflows/ci.yml
  .github/workflows/codeql.yml
  .github/workflows/ensure-triage-label.yml
  .github/workflows/issue-cleanup.yml
  .github/workflows/maintenance.yml
  .github/workflows/mark-duplicate.yml
  .github/workflows/no-response.yml
  .github/workflows/priority-support-validation-prompt.yml
  .github/workflows/scorecards.yml
  .github/workflows/support-stackoverflow.yml
  .github/workflows/vale-action.yml
  CONTRIBUTING.md
Labels: core

#25 [core][enhancement] Disable WeakRef usage in WyW modulate evaluation
  packages/pigment-css-unplugin/src/index.ts
  packages/pigment-css-vite-plugin/src/vite-plugin.ts
Labels: enhancement

#24 [core] Update the versions & changelog to reflect the last release
  CHANGELOG.md
  package.json
  packages/pigment-css-nextjs-plugin/package.json
  packages/pigment-css-react/package.json
  packages/pigment-css-unplugin/package.json
  packages/pigment-css-vite-plugin/package.json
Labels: core

#27 [release] v0.0.8
  CHANGELOG.md
  package.json
  packages/pigment-css-nextjs-plugin/package.json
  packages/pigment-css-react/package.json
  packages/pigment-css-unplugin/package.json
  packages/pigment-css-vite-plugin/package.json
Labels: release

#28 [core][fix] Use wildcard for exports instead of individual paths
  packages/pigment-css-react/package.json
Labels: bug 🐛

#30 [core] Enable release:changelog in CI
  .github/workflows/ci.yml
Labels: core

#32 [release] v0.0.9
  CHANGELOG.md
  package.json
  packages/pigment-css-nextjs-plugin/package.json
  packages/pigment-css-react/package.json
  packages/pigment-css-unplugin/package.json
  packages/pigment-css-vite-plugin/package.json
Labels: release

#38 [nextjs][bug] Transform !important css to an intermediate representation
  packages/pigment-css-nextjs-plugin/src/virtual-css-loader.js
  packages/pigment-css-unplugin/src/index.ts
  packages/pigment-css-unplugin/tsconfig.json
Labels: nextjs

#40 Fix styled inheritance
  packages/pigment-css-react/src/styled.js
  packages/pigment-css-react/tests/styled/runtime-styled.test.js
Labels: bug 🐛

#41 Bump `@wyw-in-js/*` to 0.5.3
  packages/pigment-css-react/package.json
  packages/pigment-css-unplugin/package.json
  packages/pigment-css-vite-plugin/package.json
  pnpm-lock.yaml
Labels: dependencies
