Repository mui/pigment-css, pull requests merged in 2024-06, with the labels that each got.

#31 [react] Add `globalCss` processor
  README.md
  packages/pigment-css-react/exports/globalCss.js
  packages/pigment-css-react/src/globalCss.d.ts
  packages/pigment-css-react/src/globalCss.js
  packages/pigment-css-react/src/processors/globalCss.ts
  packages/pigment-css-react/src/utils/preprocessor.ts
  packages/pigment-css-react/tests/globalCss/fixtures/globalCss-theme.input.js
  packages/pigment-css-react/tests/globalCss/fixtures/globalCss-theme.output.css
  packages/pigment-css-react/tests/globalCss/fixtures/globalCss-theme.output.js
  packages/pigment-css-react/tests/globalCss/fixtures/globalCss.input.js
  packages/pigment-css-react/tests/globalCss/fixtures/globalCss.output.css
  packages/pigment-css-react/tests/globalCss/fixtures/globalCss.output.js
  packages/pigment-css-react/tests/globalCss/globalCss.test.ts
  packages/pigment-css-react/tsup.config.ts
Labels: new feature

#112 [react] Add `createExtendSxProp` for Material UI integration
  packages/pigment-css-react/exports/internal_createExtendSxProp.js
  packages/pigment-css-react/package.json
  packages/pigment-css-react/src/createExtendSxProp.d.ts
  packages/pigment-css-react/src/createExtendSxProp.js
  packages/pigment-css-react/src/index.ts
  packages/pigment-css-react/src/processors/createExtendSxProp.ts
  packages/pigment-css-react/tests/createExtendSxProp/createExtendSxProp.test.ts
  packages/pigment-css-react/tests/createExtendSxProp/fixtures/extendSxProp.input.js
  packages/pigment-css-react/tests/createExtendSxProp/fixtures/extendSxProp.output.css
  packages/pigment-css-react/tests/createExtendSxProp/fixtures/extendSxProp.output.js
  packages/pigment-css-react/tests/createExtendSxProp/runtime-createExtendSxProp.test.js
  packages/pigment-css-react/tests/testUtils.ts
  packages/pigment-css-react/tsup.config.ts
Labels: enhancement

#105 [core] Implement useTheme processor and runtime theme
  packages/pigment-css-react/exports/useTheme.js
  packages/pigment-css-react/package.json
  packages/pigment-css-react/src/RtlProvider.tsx
  packages/pigment-css-react/src/index.ts
  packages/pigment-css-react/src/processors/useTheme.ts
  packages/pigment-css-react/src/useTheme.d.ts
  packages/pigment-css-react/src/useTheme.js
  packages/pigment-css-react/src/utils/generateThemeSource.ts
  packages/pigment-css-react/src/utils/index.ts
  packages/pigment-css-react/tests/testUtils.ts
  packages/pigment-css-react/tests/useTheme/fixtures/useTheme.input.js
  packages/pigment-css-react/tests/useTheme/fixtures/useTheme.output.css
  packages/pigment-css-react/tests/useTheme/fixtures/useTheme.output.js
  packages/pigment-css-react/tests/useTheme/generateThemeSource.test.ts
  packages/pigment-css-react/tests/useTheme/useTheme.test.tsx
  packages/pigment-css-react/tsup.config.ts
  packages/pigment-css-unplugin/src/index.ts
  packages/pigment-css-vite-plugin/src/index.ts
  pnpm-lock.yaml
Labels: new feature

#121 [docs] Add logo to the README
  README.md
Labels: docs

#123 v0.0.12
  CHANGELOG.md
  package.json
  packages/pigment-css-nextjs-plugin/package.json
  packages/pigment-css-react/package.json
  packages/pigment-css-unplugin/package.json
  packages/pigment-css-vite-plugin/package.json
Labels: release

#57 Decouple `sx` prop from system and add docs
  README.md
  packages/pigment-css-react/src/utils/extendTheme.ts
  packages/pigment-css-react/src/utils/processCssObject.ts
  packages/pigment-css-react/tests/sx/fixtures/sx-jsx.output.css
  packages/pigment-css-react/tests/sx/fixtures/sx-shorthand.output.css
  packages/pigment-css-react/tests/sx/fixtures/sxProps.input.js
  packages/pigment-css-react/tests/sx/fixtures/sxProps.output.css
  packages/pigment-css-react/tests/sx/fixtures/sxProps2.input.js
  packages/pigment-css-react/tests/sx/fixtures/sxProps2.output.css
  packages/pigment-css-react/tests/sx/visuallyHidden.js
Labels: docs

#135 v0.0.13
  CHANGELOG.md
  package.json
  packages/pigment-css-nextjs-plugin/package.json
  packages/pigment-css-react/package.json
  packages/pigment-css-unplugin/package.json
  packages/pigment-css-vite-plugin/package.json
Labels: release

#136 [unplugin] Fix the path check for Windows
  packages/pigment-css-unplugin/src/index.ts
Labels: bug 🐛

#137 v0.0.14
  CHANGELOG.md
  package.json
Labels: release

#138 v0.0.14 (2)
  packages/pigment-css-nextjs-plugin/package.json
  packages/pigment-css-unplugin/package.json
Labels: release

#146 [react] Create Hidden component
  apps/pigment-css-next-app/src/app/hidden/page.tsx
  packages/pigment-css-react/package.json
  packages/pigment-css-react/src/Hidden.d.ts
  packages/pigment-css-react/src/Hidden.jsx
  packages/pigment-css-react/src/generateAtomics.js
  packages/pigment-css-react/src/index.ts
  packages/pigment-css-react/src/utils/valueToLiteral.test.ts
  packages/pigment-css-react/src/utils/valueToLiteral.ts
  packages/pigment-css-react/tests/Hidden/Hidden.test.js
  packages/pigment-css-react/tests/Hidden/fixtures/Hidden.output.css
  packages/pigment-css-react/tests/Hidden/fixtures/Hidden.output.js
  packages/pigment-css-react/tests/generateAtomics.test.js
  packages/pigment-css-react/tests/testUtils.ts
  packages/pigment-css-react/tsup.config.ts
Labels: component: Hidden

#150 [core] Update package manager to follow core repo
  .circleci/config.yml
  package.json
  pnpm-lock.yaml
Labels: dependencies

#148 [react] Export `globalCss` from index
  package.json
  packages/pigment-css-react/package.json
  packages/pigment-css-react/src/index.spec.ts
  packages/pigment-css-react/src/index.ts
  pnpm-lock.yaml
  scripts/cli.js
Labels: bug 🐛

#149 [react] Remove sx transform logic and leverage Emotion unitless
  packages/pigment-css-react/src/utils/cssFnValueToVariable.ts
  packages/pigment-css-react/src/utils/cssFunctionTransformerPlugin.ts
  packages/pigment-css-react/tests/sx/fixtures/sx-shorthand.output.js
Labels: enhancement

#126 [code-infra] Propagate pnpm engine in package.json
  .circleci/config.yml
Labels: scope: code-infra

#153 [unplugin] Fix misuse variable to transform libraries
  packages/pigment-css-unplugin/src/index.ts
Labels: bug 🐛

#155 [react] Support transpiled library for `globalCss` and `keyframes`
  packages/pigment-css-react/src/processors/globalCss.ts
  packages/pigment-css-react/src/processors/keyframes.ts
  packages/pigment-css-react/tests/globalCss/fixtures/globalCss-theme.input.js
  packages/pigment-css-react/tests/globalCss/fixtures/globalCss-theme.output.css
  packages/pigment-css-react/tests/globalCss/fixtures/globalCss-theme.output.js
  packages/pigment-css-react/tests/keyframes/fixtures/keyframes-theme.input.js
  packages/pigment-css-react/tests/keyframes/fixtures/keyframes-theme.output.css
  packages/pigment-css-react/tests/keyframes/fixtures/keyframes-theme.output.js
Labels: bug 🐛

#156 [core] Update package manager to 9.4.0
  package.json
Labels: core

#144 [react] Create Grid component
  apps/pigment-css-next-app/src/app/grid/demo3.tsx
  apps/pigment-css-next-app/src/app/grid/page.tsx
  apps/pigment-css-vite-app/src/pages/grid.tsx
  packages/pigment-css-react/package.json
  packages/pigment-css-react/src/Grid.d.ts
  packages/pigment-css-react/src/Grid.jsx
  packages/pigment-css-react/src/Stack.jsx
  packages/pigment-css-react/src/generateAtomics.js
  packages/pigment-css-react/src/processors/styled.ts
  packages/pigment-css-react/src/utils/convertAtomicsToCss.ts
  packages/pigment-css-react/tests/Container/fixtures/Container.output.js
  packages/pigment-css-react/tests/Grid/Grid.spec.tsx
  packages/pigment-css-react/tests/Grid/Grid.test.js
  packages/pigment-css-react/tests/Grid/fixtures/Grid.output.css
  packages/pigment-css-react/tests/Grid/fixtures/Grid.output.js
  packages/pigment-css-react/tests/Hidden/fixtures/Hidden.output.js
  packages/pigment-css-react/tests/generateAtomics.test.js
  packages/pigment-css-react/tsup.config.ts
Labels: component: Grid

#158 v0.0.15
  CHANGELOG.md
  package.json
  packages/pigment-css-nextjs-plugin/package.json
  packages/pigment-css-react/package.json
  packages/pigment-css-unplugin/package.json
  packages/pigment-css-vite-plugin/package.json
Labels: release

#159 [Grid] Add wrap prop
  apps/pigment-css-vite-app/src/pages/grid.tsx
  packages/pigment-css-react/src/Grid.d.ts
  packages/pigment-css-react/src/Grid.jsx
  packages/pigment-css-react/tests/Grid/fixtures/Grid.output.css
  packages/pigment-css-react/tests/Grid/fixtures/Grid.output.js
Labels: component: Grid

#160 [nextjs] Make library path check OS agnostic
  packages/pigment-css-unplugin/src/index.ts
  packages/pigment-css-vite-plugin/src/index.ts
Labels: nextjs

#161 v0.0.16
  CHANGELOG.md
  package.json
  packages/pigment-css-nextjs-plugin/package.json
  packages/pigment-css-react/package.json
  packages/pigment-css-unplugin/package.json
  packages/pigment-css-vite-plugin/package.json
  pnpm-lock.yaml
Labels: release
