Repository mui/pigment-css, pull requests merged in 2024-05, with the labels that each got.

#43 Fix prop forwarding when `as` component is provided to HTML styled component
  packages/pigment-css-react/src/styled.js
  packages/pigment-css-react/tests/styled/runtime-styled.test.js
Labels: bug 🐛

#42 v0.0.10
  CHANGELOG.md
  packages/pigment-css-nextjs-plugin/package.json
  packages/pigment-css-react/package.json
  packages/pigment-css-unplugin/package.json
  packages/pigment-css-vite-plugin/package.json
Labels: release

#44 [core] Set root version to 0.0.10
  CHANGELOG.md
  package.json
Labels: core

#37 Enable `sx` prop on any components
  apps/pigment-css-next-app/.eslintrc
  apps/pigment-css-next-app/next.config.js
  apps/pigment-css-next-app/src/app/page.tsx
  apps/pigment-css-next-app/tsconfig.json
  package.json
  packages/pigment-css-react/.gitignore
  packages/pigment-css-react/package.json
  packages/pigment-css-react/src/private-runtime/ForwardSx.js
  packages/pigment-css-react/src/private-runtime/index.ts
  packages/pigment-css-react/src/processors/sx.ts
  packages/pigment-css-react/src/styled.js
  packages/pigment-css-react/src/sx.js
  packages/pigment-css-react/src/utils/spreadSxProp.ts
  packages/pigment-css-react/src/utils/sx-plugin.ts
  packages/pigment-css-react/tests/Box/fixtures/box-jsx.input.js
  packages/pigment-css-react/tests/Box/fixtures/box-jsx.output.css
  packages/pigment-css-react/tests/Box/fixtures/box-jsx.output.js
  packages/pigment-css-react/tests/Box/fixtures/box.output.css
  packages/pigment-css-react/tests/Box/fixtures/box.output.js
  packages/pigment-css-react/tests/sx/fixtures/sx-jsx.input.js
  packages/pigment-css-react/tests/sx/fixtures/sx-jsx.output.css
  packages/pigment-css-react/tests/sx/fixtures/sx-jsx.output.js
  packages/pigment-css-react/tests/sx/fixtures/sxProps.input.js
  packages/pigment-css-react/tests/sx/fixtures/sxProps.output.css
  packages/pigment-css-react/tests/sx/fixtures/sxProps.output.js
  packages/pigment-css-react/tests/sx/fixtures/sxProps2.output.css
  packages/pigment-css-react/tests/sx/fixtures/sxProps2.output.js
  packages/pigment-css-react/tests/sx/sx.test.ts
  packages/pigment-css-react/tsup.config.ts
  pnpm-lock.yaml
Labels: new feature

#51 Replace `sx` callback object param with `theme`
  packages/pigment-css-react/src/processors/sx.ts
  packages/pigment-css-react/tests/sx/fixtures/sx-jsx.input.js
  packages/pigment-css-react/tests/sx/fixtures/sxProps2.input.js
Labels: bug 🐛

#52 Support array for `sx` prop
  packages/pigment-css-react/src/processors/sx.ts
  packages/pigment-css-react/src/sx.d.ts
  packages/pigment-css-react/src/sx.js
  packages/pigment-css-react/src/utils/cssFunctionTransformerPlugin.ts
  packages/pigment-css-react/src/utils/spreadSxProp.ts
  packages/pigment-css-react/src/utils/sx-plugin.ts
  packages/pigment-css-react/src/utils/sxPropConverter.ts
  packages/pigment-css-react/tests/sx/fixtures/sx-array.input.js
  packages/pigment-css-react/tests/sx/fixtures/sx-array.output.css
  packages/pigment-css-react/tests/sx/fixtures/sx-array.output.js
  packages/pigment-css-react/tests/sx/fixtures/sx-jsx.input.js
  packages/pigment-css-react/tests/sx/fixtures/sx-jsx.output.css
  packages/pigment-css-react/tests/sx/fixtures/sx-jsx.output.js
  packages/pigment-css-react/tests/sx/fixtures/sx-shorthand.input.js
  packages/pigment-css-react/tests/sx/fixtures/sx-shorthand.output.css
  packages/pigment-css-react/tests/sx/fixtures/sx-shorthand.output.js
  packages/pigment-css-react/tests/sx/fixtures/sxProps.input.js
  packages/pigment-css-react/tests/sx/fixtures/sxProps.output.css
  packages/pigment-css-react/tests/sx/fixtures/sxProps.output.js
  packages/pigment-css-react/tests/sx/sx-runtime.test.js
  packages/pigment-css-react/tests/sx/sx.test.ts
  packages/pigment-css-react/tests/sx/visuallyHidden.js
Labels: enhancement

#54 [styled] Replace lowercase with lowerFirst
  packages/pigment-css-react/src/processors/styled.ts
  packages/pigment-css-react/src/utils/lowercaseFirstLetter.ts
  packages/pigment-css-react/tests/styled/fixtures/styled-theme-styleOverrides.input.js
  packages/pigment-css-react/tests/styled/fixtures/styled-theme-styleOverrides.output.css
  packages/pigment-css-react/tests/styled/fixtures/styled-theme-styleOverrides.output.js
  packages/pigment-css-react/tests/styled/styled.test.tsx
Labels: bug 🐛

#58 v0.0.11
  CHANGELOG.md
  package.json
  packages/pigment-css-nextjs-plugin/package.json
  packages/pigment-css-react/package.json
  packages/pigment-css-unplugin/package.json
  packages/pigment-css-vite-plugin/package.json
Labels: release

#60 [docs] Fix roadmap link
  examples/pigment-css-nextjs-ts/src/app/page.tsx
  examples/pigment-css-remix-ts/app/routes/_index.tsx
  examples/pigment-css-vite-ts/src/App.tsx
Labels: docs

#63 [core] Cleanup
  SECURITY.md
  babel.config.js
  package.json
  packages/pigment-css-unplugin/package.json
  pnpm-lock.yaml
  renovate.json
  test/README.md
  test/assets/fake.png
  test/assets/fake2.png
  test/cli.js
  test/docs-regressions-before.png
  test/docs-regressions-diff.png
  test/karma.conf.js
  test/karma.conf.profile.js
  test/karma.tests.js
  test/package.json
  test/regressions/.mocharc.js
  test/regressions/README.md
  test/regressions/TestViewer.js
  test/regressions/fixtures/.gitkeep
  test/regressions/index.js
  test/regressions/index.test.js
  test/regressions/manual/README.md
  test/regressions/serve.json
  test/regressions/template.html
  test/regressions/webpack.config.js
  test/tsconfig.json
Labels: core

#70 [docs] Improve wording
  HOW_PIGMENT_CSS_WORKS.md
Labels: docs

#75 [examples] Fix instructions to run
  README.md
  examples/pigment-css-nextjs-ts/README.md
  examples/pigment-css-remix-ts/README.md
  examples/pigment-css-vite-ts/README.md
Labels: bug 🐛, examples

#103 [code-infra] Use shared .stylelintrc.js config
  .stylelintrc.js
Labels: scope: code-infra

#108 [fix] Make theme optional in Pigment CSS config
  packages/pigment-css-react/src/utils/generateCss.ts
  packages/pigment-css-vite-plugin/src/index.ts
Labels: bug 🐛

#106 [fix] Ignore urls starting with #
  packages/pigment-css-unplugin/src/utils.ts
  packages/pigment-css-unplugin/tests/utils.test.ts
Labels: bug 🐛

#111 [fix] Implement variant matching parity
  packages/pigment-css-react/src/styled.js
Labels: bug 🐛

#110 [docs] Fix styleOverrides usage in README
  README.md
Labels: docs

#113 [core-infra] Use test-utils pacakge from npm
  package.json
  pnpm-lock.yaml
  prettier.config.js
Labels: scope: code-infra
